travis:
  secure:
    BINSTAR_TOKEN: evNG13voGPZfqx9Kc9xHGQpaYllVBbKS4qR06ddymm4x2RSGoKD42qzm21L+QkTjtRnFH7yW8+8S3y0bVcqJJ41tSppxlpIYJ871BzBCsoXzYKMOE4/fsHeotkWsgJFCl4BrHOXStqJf1Q3aIvoh8KBu5tvFI5Rmzl/c/Sgep3c11p4rbdtWWdhrJzyoIMLRHsLO5XOxpXTM9W+Y4XSMzR94+HP+nu5fsG5t4CfbxCNBeuO7eOF5ofg91xM5lYWMPRxixiwFUl5usoYDNuEb7Qvlwt5lxvwLvqdxuaFfBPKK3wKSgxpctw2wSxEpmQLeWhC9qW2qJgeIJyda6zGnc6qetFYcVX65XhyNAO2bp/MP7UwYSM5bl5lHbhbTR4IGrbVZ9DDS5nawL2vlDnTQtVI5yAkMi568Caxxhttiu/gpPb6KN1loQp/7hYyxWE1/FY3lMefmdI4Z96TN4YXAZg3OhxpLAjrRkbDO3IDvpq49gfzodzZUOHghhEnVMIOePvk2e8iYcumAOFGjr/GvJcfZg4UOpblmQDsCNoq/Ah+GcO9kftOfpqVI5jx59ato1p5/8/7LwQRhpqcTPWZHOKFTUHhvtXkciuI59AMg114Qt8fhPRd++qyPIX9Gu7Y9lnWT7emTZrmFBOBWM18WvynaMrUthTRSSK/dfDFoFgo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
