travis:
  secure:
    BINSTAR_TOKEN: FPt+PefQHJ7XIENrK+lLtxpsCy5QFxrdXAaZEbGAj2sHyWfGDji0Ha7HLejWhkh5ST/mpKIziWxO6N1l4APLlYBEFDP+cejNiPRyXVrecR/q8cTgR4B7OqoGSZYM3cvKY0lNOavMiBwhwVFycfPVQGLIKq46A3iypAeKYuD8SjQl2DcfUy33jVrECSTuqjE/Vc/jVpWeovtblgIhCjfKomgdxlJkhTgdu5p8WFyW/uPtF4SQaEolSfXGtM4FLLM5sVSIVsTDAA5BODPWP9yN6WK/4Cc5C9Rh8gZ/tdvx7nO2LN3v7pgNG8inhYiGXaz4Mmxg09xP82DI/Qk3IbbTrS8e71zMcYHxsV/9/FL1j0uG/5TLycUuZcg4KJvgUv8C4SZUDuhgPXA0sT0TpbgbgLaRtHqE50eXaqKeBWQe4wXGYqp3IPgvs05WcWaE/C3Nm6b9s6pJmNrdpLzpej3QvnXEuLCoEgCqK1SPlH9H9A9fWrosYEFBfhC6I9SILXT7cN5IgpeyZBRnlotvf7Ej4F3ylGKEIBi0JVsJwdQmqPfXayjN5kgJu55oA9Qan3rFO+kWc5TE/3BDVGuxmTyyXkw+YMXtGrlxiGYMVOaiJ0A/YmAYPjW9eYOevfuT62zPHVOHokFgT5Zi43oS+xtx59f/k5pPr5v7pKUNEMsiw0Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
