travis:
  secure:
    BINSTAR_TOKEN: fhTqiQz8Ib/yK1sJ2c+av6Z6UcK64JfPaMuN636ikgWvu+iMZfCZRYhC63b7fDdU/othNezsWRItRCqJVQTJjq1eMUrqiFTxDCEgx65ScYoe/eumfEX8gndzBEi3KzOQzcwfhfCWHPMIcBtGo9cCXpOLg9zasnJLcor2YMoRSvANBZg1TswBOXOKzHKoAP7irsTDN3QDAZ1anvCRcuiwz6rNuZ5WdY4YQBGju3j4SuP68GuxdVc9+yVEY5xf/4y4JFyAmWXVZCgBDNZ3endGaFk0qaoshxqZvyrzU82BFhPvobW+CRQkoTPD0UnhfDye0FgsaSIdKYy8T3xm6K3ZSNSFLJHwFfK1INGpHHickn/krimfovzyy9fYLwOGGsmWDZlZTxhfOJl+HbFQvvF/L1Z8jv7VTC2qhiXu/rDVidVfRy6gnC+28T+AIPvbk/Ug7SnRcQWw8kdK/Hd4w360n4jn1hnRhgFn1/FO1zxPZoia/94DueRFd1tjKEsyav0G/OpCyDsbRVLBbyDHT3mkSgZy08E2INMmA7Kp+AQCqYAh12/RNxDKf5osGBmPdAhF1yVD0vUhNL8/i4gbD10r76UvfagZFFBoXH94gIfprdS7DkhyeDrWNHqOWAltXNl4Xo/xSbEVimWIKzc8XoJil9KuyNvkEs7cUOo8j9smZtw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
