travis:
  secure:
    BINSTAR_TOKEN: MbbNavdPJn1WWtNLZSCLDOhHjOhsT+ca0jMCZDF76FIVfKJuWc7z1ddAZOYxmsk5CxKd+y38mbl/OUcc/DBv0ryFOZny9fxlWiB13NHAbavUe+crv7o0calm17Z+VxKeiFx46URz0vd6fN/AbZP8vLqSFEu4AduFwZHq7wVON1P5fd8wAAMZOU74BpbtCRsTmWpo1dtpgUK4gwqf0P9Fp57AU5tJx338epM6I2FvE6rjpWj+2FHXpDjzKKdWdKusJ+eufPAeN9s5IZjIPyr6Hotxd5QALIAlz6SIg3BLrFgZC1UpGGUSp8Q6mQOoRWUNYJAyQkdY501WoRoUlnKqDKrDAUQsw4NQKUdHwac7mptjwc2mPbgHgy04s4Q6EZqk/z7ze6NkCmTVkgWXllpkkUkruAw4NE3GA4fXt0f5yyDY7QlDg+k3hI9k2VR6cxuS7y1spzC7l2PFYdlUSeeg4qobQHbXjV0iE+80ondcvpLzfa/2HJPbwdjhXBS5sxmDw2GvhzuAZGoFkryaD8Nd/bWOH5uJ0dV1iCY6Sqz18RIBJIlj5ZFcmjnl1ZAxVmwPIgDEsenu9tLQXnhzoiOW8r+MbgJYNpC5eCxvarunmV9BU3eLdpMuWp3ldBNS+g3E8dPz+1IRGkzcAMp0MXiLlec+GWtqFfaKRMb6FeFjmiA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
