appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ZEzcjTFSaOp+6so5omMma7xNVDRrGwwh3GOWcgT3oNyykObdbqDXW9WJw78iMlTcwWeZnXC+J+L7KCqah+mUAUjILTSlJBu+7UVdmVuUU5DKsINw8DSz7PZcKSoCoDW5lfth2k/eTiMMzCQc3yAUwZ6Ji/iA2KWmK875WqQfhMI+WIAoQccdMz0Ogww4b1zeM46bUh9GnLsMoOyj0icQj5QlVIGmg0Ov/NZLU1PfdR1KwYlVRmM2WG4AvCKW3x2+WldEdnDJBciis8X7SWucZu58c/s2FiOFwbZlv4hswOafR25/nvlvubGjyJLcmZHJlleOISE1wyBb1x8q7jFF9ODcOM16PQ3ZnW7Kfdph1Cf1MxXRaL4zMv3lv+JSfChJAn+iP7yIe31W3dlwc1H1FNpcWbTbT3SqDm1akqDwKC8e24+odNEzoHrLem36alGguMxKx9VT/XGMM9uRjosFKrx2+4+lkIdFT2eOIxNlb0tx+eCrS3maCDFFMAKHOar3xnmYJHosCdAONZIHKA8z6Q6r288LuUiJmoZjdPiQxKfAmqn2Lnwj0FmBLW53TfUcRggv5o6Dmpkoc5/3zsbCfiCiTr3kjd0uEUkBobrD0BqNvki5HEVJEqLvPTATQAs3/ClLOByoki35uutnSKknykn9y/+Ad0TCjlgmJuUI2x4=}
